In [1]:
from bs4 import BeautifulSoup
import requests
import os
import random
import pandas as pd
import numpy as np
import re

In [2]:
#def grab_webpage(location):
url = 'http://rosettacode.org/wiki/I_before_E_except_after_C'
page = requests.get(url)
soup = BeautifulSoup(page.content)
#print(soup.prettify())
all_headers = soup.findAll("h2")
type(all_headers[0])

bs4.element.Tag

In [202]:
def bret_classifier(snippet):
    languages = ["clojure", "python", "javascript", "ruby", "haskell", "scheme", "java", "scala", "tcl", "php", "ocaml"]
    return random.choice(languages)

In [203]:
bret_classifier("set: var = python ++ & programming")

'javascript'

In [204]:
def test_classification(classifier_function):
    for filename in os.listdir('test'):
        file = open('test/' + filename)
        program_text = file.read()
        #print(program_text)
        print(classifier_function(program_text))

In [205]:
test_classification(bret_classifier)

php
javascript
java
javascript
java
php
php
python
python
tcl
clojure
ocaml
ocaml
java
ruby
tcl
scala
javascript
clojure
ocaml
ruby
ocaml
clojure
php
haskell
ruby
scala
ocaml
java
python
scala
python


In [206]:
possible_factors = [r"$", r"def", r"end", r"{", r"}", r"&"]
file_extensions = {".py": "python",
                   ".rb": "ruby",
                   ".ruby": "ruby",
                   ".jruby": "ruby",
                   ".python": "python",
                   ".clojure": "clojure",
                   ".php": "php",
                   ".ocaml": "ocaml",
                   ".java": "java",
                   ".javascript": "javascript",
                   ".python3": "python",
                   ".racket": "scheme",
                   ".ghc": "haskell",
                   ".tcl": "tcl",
                   ".scala": "scala",
                   }
all_extensions = set()
for root, dirs, files in os.walk("benchmarksgame-2014-08-31/"):
    for filed in files:
        all_extensions.add(os.path.splitext(filed)[1])
print(all_extensions)

{'', '.py', '.rust', '.perl', '.gnat', '.c', '.conf', '.java', '.ozf', '.javasteady', '.txt', '.hack', '.oz', '.sbcl', '.erlang', '.ifc', '.lua', '.ini', '.javascript', '.csharp', '.fpascal', '.lang', '.python3', '.parrot', '.cint', '.bash', '.vw', '.dart', '.gcc', '.python', '.ghc', '.ats', '.ocaml', '.gpp', '.jruby', '.yarv', '.fsharp', '.go', '.clojure', '.h', '.cc', '.Makefile', '.scala', '.php', '.racket'}


In [207]:
def get_training_samples(directory, extension_dict):
    "Read in the examples, kick out a list of tuples of text and classifications."
    text_list = []
    lang_list = []
    for root, dirs, files in os.walk(directory):
        for particular_file in files:
            extension = os.path.splitext(particular_file)[1]
            if extension in file_extensions:
                #print("Yay! " + particular_file)
                #print(os.path.join(root, particular_file))
                try:
                    file_in = open(os.path.join(root, particular_file))
                    text = file_in.read()
                    #print(text)
                    text_list.append(text)
                    lang_list.append(extension_dict[extension])
                except:
                    print("hiccuped on : " + particular_file)
    df = pd.DataFrame({"code": text_list,
                       "language": lang_list})
    return df
    

In [208]:
training_data = get_training_samples("benchmarksgame-2014-08-31/", file_extensions)

hiccuped on : pidigits.ocaml-2.ocaml


In [209]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 367 entries, 0 to 366
Data columns (total 2 columns):
code        367 non-null object
language    367 non-null object
dtypes: object(2)
memory usage: 8.6+ KB


In [210]:
training_data.language.value_counts()

java          52
python        50
scala         43
clojure       38
ocaml         34
ruby          34
haskell       33
php           29
scheme        29
javascript    25
dtype: int64

In [211]:
test_regex = re.compile(r"def")
test_regex_2 = re.compile(r"var")
test_regex_objects = [test_regex, test_regex_2]
def text_factors(snippet, regex_objects):
    "Takes a code snippet and returns a vector of features in [0,1]"
    normalizing_factor = len(snippet)
    factors = []
    for factor in range(len(regex_objects)):
        target = regex_objects[factor]
        total_num = len(target.findall(snippet))
        frequency = total_num / normalizing_factor
        factors.append(frequency)
    factor_array = np.array(factors)    
    return factor_array

In [212]:
text_factors(training_data.iloc[0,0], test_regex_objects)

array([ 0.00454545,  0.        ])

In [213]:
type(test_regex.findall(training_data.iloc[0,0]))

list

In [214]:
print(text_factors(training_data.iloc[0,0], test_regex_objects))

[ 0.00454545  0.        ]


In [215]:
type(text_factors(training_data.iloc[0,0], test_regex_objects))

numpy.ndarray

In [216]:
def compile_regex_objects(factors):
    "Given possible strings in the code, return a list of regex objects that can match for them."
    objects = []
    for factor in factors:
        current_object = re.compile(factor)
        objects.append(current_object)
    return objects

In [217]:
regex_list = compile_regex_objects(possible_factors)

In [218]:
regex_list

[re.compile(r'$', re.UNICODE),
 re.compile(r'def', re.UNICODE),
 re.compile(r'end', re.UNICODE),
 re.compile(r'{', re.UNICODE),
 re.compile(r'}', re.UNICODE),
 re.compile(r'&', re.UNICODE)]

In [219]:
text_factors(training_data.iloc[9,0], regex_list)

array([ 0.00146199,  0.        ,  0.        ,  0.00511696,  0.00511696,  0.        ])

In [220]:
test_array = np.zeros((10, 1))

In [221]:
test_array[2] = 1

In [222]:
test_array.reshape(1, -1).reshape(-1, 1)

array([[ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [223]:
import theano

In [8]:
autohotkey = soup.find("pre")

In [15]:
autohotkey.get_text()

'WordList := URL_ToVar("http://www.puzzlers.org/pub/wordlists/unixdict.txt")WordList := RegExReplace(WordList, "i)cie", "", cieN)WordList := RegExReplace(WordList, "i)cei", "", ceiN)RegExReplace(WordList, "i)ie", "", ieN)RegExReplace(WordList, "i)ei", "", eiN)\xa0cei := ceiN / cieN > 2\xa0? "plausible"\xa0: "implausible"ei  := ieN  / eiN  > 2\xa0? "plausible"\xa0: "implausible"ova := cei = "plausible." && ei = "plausible"\xa0? "plausible"\xa0: "implausible"\xa0MsgBox,\xa0% """I before E when not preceded by C"" is " ei ".`n"        . ieN " cases for and " eiN " cases against is a ratio of " ieN / eiN ".`n`n"        . """E before I when preceded by C"" is " cei ".`n"        . ceiN " cases for and " cieN " cases against is a ratio of " ceiN / cieN ".`n`n"        . "Overall the rule is " ova "."\xa0URL_ToVar(URL) {    WebRequest := ComObjCreate("WinHttp.WinHttpRequest.5.1")    WebRequest.Open("GET", URL)    WebRequest.Send()    return, WebRequest.ResponseText}'

WordList := URL_ToVar("http://www.puzzlers.org/pub/wordlists/unixdict.txt")
WordList := RegExReplace(WordList, "i)cie", "", cieN)
WordList := RegExReplace(WordList, "i)cei", "", ceiN)
RegExReplace(WordList, "i)ie", "", ieN)
RegExReplace(WordList, "i)ei", "", eiN)
 
cei := ceiN / cieN > 2 ? "plausible" : "implausible"
ei  := ieN  / eiN  > 2 ? "plausible" : "implausible"
ova := cei = "plausible." && ei = "plausible" ? "plausible" : "implausible"
 
MsgBox, % """I before E when not preceded by C"" is " ei ".`n"
        . ieN " cases for and " eiN " cases against is a ratio of " ieN / eiN ".`n`n"
        . """E before I when preceded by C"" is " cei ".`n"
        . ceiN " cases for and " cieN " cases against is a ratio of " ceiN / cieN ".`n`n"
        . "Overall the rule is " ova "."
 
URL_ToVar(URL) {
    WebRequest := ComObjCreate("WinHttp.WinHttpRequest.5.1")
    WebRequest.Open("GET", URL)
    WebRequest.Send()
    return, WebRequest.ResponseText
}

In [49]:
"".join([string for string in autohotkey.strings])

'WordList := URL_ToVar("http://www.puzzlers.org/pub/wordlists/unixdict.txt")WordList := RegExReplace(WordList, "i)cie", "", cieN)WordList := RegExReplace(WordList, "i)cei", "", ceiN)RegExReplace(WordList, "i)ie", "", ieN)RegExReplace(WordList, "i)ei", "", eiN)\xa0cei := ceiN / cieN > 2\xa0? "plausible"\xa0: "implausible"ei  := ieN  / eiN  > 2\xa0? "plausible"\xa0: "implausible"ova := cei = "plausible." && ei = "plausible"\xa0? "plausible"\xa0: "implausible"\xa0MsgBox,\xa0% """I before E when not preceded by C"" is " ei ".`n"        . ieN " cases for and " eiN " cases against is a ratio of " ieN / eiN ".`n`n"        . """E before I when preceded by C"" is " cei ".`n"        . ceiN " cases for and " cieN " cases against is a ratio of " ceiN / cieN ".`n`n"        . "Overall the rule is " ova "."\xa0URL_ToVar(URL) {    WebRequest := ComObjCreate("WinHttp.WinHttpRequest.5.1")    WebRequest.Open("GET", URL)    WebRequest.Send()    return, WebRequest.ResponseText}'

In [54]:
print(autohotkey.get_text())

WordList := URL_ToVar("http://www.puzzlers.org/pub/wordlists/unixdict.txt")WordList := RegExReplace(WordList, "i)cie", "", cieN)WordList := RegExReplace(WordList, "i)cei", "", ceiN)RegExReplace(WordList, "i)ie", "", ieN)RegExReplace(WordList, "i)ei", "", eiN) cei := ceiN / cieN > 2 ? "plausible" : "implausible"ei  := ieN  / eiN  > 2 ? "plausible" : "implausible"ova := cei = "plausible." && ei = "plausible" ? "plausible" : "implausible" MsgBox, % """I before E when not preceded by C"" is " ei ".`n"        . ieN " cases for and " eiN " cases against is a ratio of " ieN / eiN ".`n`n"        . """E before I when preceded by C"" is " cei ".`n"        . ceiN " cases for and " cieN " cases against is a ratio of " ceiN / cieN ".`n`n"        . "Overall the rule is " ova "." URL_ToVar(URL) {    WebRequest := ComObjCreate("WinHttp.WinHttpRequest.5.1")    WebRequest.Open("GET", URL)    WebRequest.Send()    return, WebRequest.ResponseText}
